multitenancy:
  datasources:
    one:
      url: jdbc:hsqldb:file:target/tenant_one_db
      username: SA
      password:
    two:
      url: jdbc:hsqldb:file:target/tenant_two_db
      username: SA
      password:
spring:
  jpa:
    hibernate:
      ddl-auto: none